<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('exercises')->insert([
            ['name'=>'Air Bike M Waist Fix', 'folder'=>'Core','filename'=>'air-bike-m_waist_fix.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Air Twisting Crunch Waist', 'folder'=>'Core','filename'=>'air-twisting-crunch_waist.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Alternate Lying Floor Leg Raise Waist  ', 'folder'=>'Core','filename'=>'alternate-lying-floor-leg-raise_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Bodyweight Side Lying Biceps Curl Upper Arms ', 'folder'=>'Core','filename'=>'bodyweight-side-lying-biceps-curl_upper-arms_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Kneeling Crunch Female Waist  ', 'folder'=>'Core','filename'=>'cable-kneeling-crunch-female_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Arms Straight Waist', 'folder'=>'Core','filename'=>'crunch-arms-straight_waist.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Floor W Waist  ', 'folder'=>'Core','filename'=>'crunch-floor-w_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Hands Overhead Waist', 'folder'=>'Core','filename'=>'crunch-hands-overhead_waist.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Hands Overhead Waist  ', 'folder'=>'Core','filename'=>'crunch-hands-overhead_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Leg Raise Waist  ', 'folder'=>'Core','filename'=>'crunch-leg-raise_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Straight Leg Up Waist  ', 'folder'=>'Core','filename'=>'crunch-straight-leg-up_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dead Bug Waist ', 'folder'=>'Core','filename'=>'dead-bug_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Decline Sit Up Arms Straight Waist  ', 'folder'=>'Core','filename'=>'decline-sit-up-arms-straight_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Exercise Ball Frog Crunch Female Waist  ', 'folder'=>'Core','filename'=>'exercise-ball-frog-crunch-female_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Frog Crunch Waist  ', 'folder'=>'Core','filename'=>'frog-crunch_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Front Plank', 'folder'=>'Core','filename'=>'front-plank-990x438-410x200.png','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Hanging Leg Raise Hips ', 'folder'=>'Core','filename'=>'hanging-leg-raise_hips_360.gif','muscle_group_id'=>1,'equipment_id'=>19,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Hip Crunch Knees Bent Waist  1 ', 'folder'=>'Core','filename'=>'hip-crunch-knees-bent_waist_360-1-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Jack Knife On Ball Waist ', 'folder'=>'Core','filename'=>'jack-knife-on-ball_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Jackknife Sit Up Waist  ', 'folder'=>'Core','filename'=>'jackknife-sit-up_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Oblique Crunches Floor Waist ', 'folder'=>'Core','filename'=>'oblique-crunches-floor_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Side Plank M Waist  ', 'folder'=>'Core','filename'=>'side-plank-m_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Sit Up Ii Waist  ', 'folder'=>'Core','filename'=>'sit-up-ii_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Stability Ball Rollout On Knees Female Hips Fix ', 'folder'=>'Core','filename'=>'stability-ball-rollout-on-knees-female_hips-fix_360.gif','muscle_group_id'=>1,'equipment_id'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'V Up Down With Stability Ball Female Waist ', 'folder'=>'Core','filename'=>'v-up-down-with-stability-ball-female_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Weighted Side Bend On Stability Ball Waist  ', 'folder'=>'Core','filename'=>'weighted-side-bend-on-stability-ball_waist_360-360x200.gif','muscle_group_id'=>1,'equipment_id'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Pushdown Male Upper Arms ', 'folder'=>'Arm','filename'=>'band-pushdown-male_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Jm Bench Press Upper Arms ', 'folder'=>'Arm','filename'=>'barbell-jm-bench-press_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Lying Triceps Extension Upper Arms ', 'folder'=>'Arm','filename'=>'barbell-lying-triceps-extension_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Standing Back Wrist Curl Forearms ', 'folder'=>'Arm','filename'=>'barbell-standing-back-wrist-curl_forearms_360','muscle_group_id'=>2,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Standing Overhead Triceps Extension Upper Arms ', 'folder'=>'Arm','filename'=>'barbell-standing-overhead-triceps-extension_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Standing Reverse Grip Curl Forearms ', 'folder'=>'Arm','filename'=>'barbell-standing-reverse-grip-curl_forearms_360','muscle_group_id'=>2,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Wrist Curl Ii Forearms ', 'folder'=>'Arm','filename'=>'barbell-wrist-curl-ii_forearms_360','muscle_group_id'=>2,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Bench Dip On Floor Upper Arms ', 'folder'=>'Arm','filename'=>'bench-dip-on-floor_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Curl M Upper Arms ', 'folder'=>'Arm','filename'=>'cable-curl-m_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Kickback Upper Arms ', 'folder'=>'Arm','filename'=>'cable-kickback_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Pushdown With Rope Attachment Upper Arms ', 'folder'=>'Arm','filename'=>'cable-pushdown-with-rope-attachment_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Reverse Grip Triceps Pushdown Sz Bar Upper Arms  1', 'folder'=>'Arm','filename'=>'cable-reverse-grip-triceps-pushdown-sz-bar_upper-arms_360-1','muscle_group_id'=>2,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Standing One Arm Triceps Extension Upper Arms ', 'folder'=>'Arm','filename'=>'cable-standing-one-arm-triceps-extension_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Triceps Pushdown V Bar Attachment Upper Arms ', 'folder'=>'Arm','filename'=>'cable-triceps-pushdown-v-bar-attachment_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Close Grip Push Up Upper Arms ', 'folder'=>'Arm','filename'=>'close-grip-push-up_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Biceps Curl Reverse Upper Arms ', 'folder'=>'Arm','filename'=>'dumbbell-biceps-curl-reverse_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Kickbacks On Exercise Ball Upper Arms ', 'folder'=>'Arm','filename'=>'dumbbell-kickbacks-on-exercise-ball_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Kickback Upper Arms ', 'folder'=>'Arm','filename'=>'dumbbell-kickback_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell One Arm Reverse Preacher Curl Forearms ', 'folder'=>'Arm','filename'=>'dumbbell-one-arm-reverse-preacher-curl_forearms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Over Bench One Arm Reverse Wrist Curl Forearms ', 'folder'=>'Arm','filename'=>'dumbbell-over-bench-one-arm-reverse-wrist-curl_forearms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Peacher Hammer Curl Forearms  (1)', 'folder'=>'Arm','filename'=>'dumbbell-peacher-hammer-curl_forearms_360 (1)','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Peacher Hammer Curl Forearms ', 'folder'=>'Arm','filename'=>'dumbbell-peacher-hammer-curl_forearms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Seated Kickback Upper Arms ', 'folder'=>'Arm','filename'=>'dumbbell-seated-kickback_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Seated Revers Grip Concentration Curl Forearms ', 'folder'=>'Arm','filename'=>'dumbbell-seated-revers-grip-concentration-curl_forearms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Seated Reverse Grip One Arm Overhead Tricep Extension Upper Arms ', 'folder'=>'Arm','filename'=>'dumbbell-seated-reverse-grip-one-arm-overhead-tricep-extension_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Seated Triceps Extension Upper Arms ', 'folder'=>'Arm','filename'=>'dumbbell-seated-triceps-extension_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Standing Inner Biceps Curl Version 2 Upper Arms ', 'folder'=>'Arm','filename'=>'dumbbell-standing-inner-biceps-curl-version-2_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Tate Press Triceps ', 'folder'=>'Arm','filename'=>'dumbbell-tate-press_triceps_360','muscle_group_id'=>2,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Exercise Ball Supine Triceps Extension Upper Arms ', 'folder'=>'Arm','filename'=>'exercise-ball-supine-triceps-extension_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Ez Barbell Close Grip Curl Upper Arms ', 'folder'=>'Arm','filename'=>'ez-barbell-close-grip-curl_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>13,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Ez Barbell Curl Female Upper Arms ', 'folder'=>'Arm','filename'=>'ez-barbell-curl-female_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>13,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Ez Barbell Incline Triceps Extension Upper Arms ', 'folder'=>'Arm','filename'=>'ez-barbell-incline-triceps-extension_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>13,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Ez Barbell Reverse Grip Curl Forearms  1', 'folder'=>'Arm','filename'=>'ez-barbell-reverse-grip-curl_forearms_360-1','muscle_group_id'=>2,'equipment_id'=>13,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Triceps Dip Female Upper Arms ', 'folder'=>'Arm','filename'=>'triceps-dip-female_upper-arms_360','muscle_group_id'=>2,'equipment_id'=>10,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'45 Degree One Leg Hyperextension Arms In Front Of Chest Hips  ', 'folder'=>'Back','filename'=>'45-degree-one-leg-hyperextension-arms-in-front-of-chest_hips_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>15,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'45 Degree Twisting Hyperextension Hips  1', 'folder'=>'Back','filename'=>'45-degree-twisting-hyperextension_hips_360-1.gif','muscle_group_id'=>3,'equipment_id'=>15,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Assisted Pull Up Back  ', 'folder'=>'Back','filename'=>'assisted-pull-up_back_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>1,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Bent Shoulders Over Rear Lateral Raise Shoulders  ', 'folder'=>'Back','filename'=>'band-bent_shoulders-over-rear-lateral-raise_shoulders_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Kneeling One Arm Pulldown Back  ', 'folder'=>'Back','filename'=>'band-kneeling-one-arm-pulldown_back_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Pull Apart Shoulders  ', 'folder'=>'Back','filename'=>'band-pull-apart_shoulders_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Twist Down Up Waist  ', 'folder'=>'Back','filename'=>'band-twist-down-up_waist_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Deadlift Female Hips  ', 'folder'=>'Back','filename'=>'barbell-deadlift-female_hips_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Good Morning Female Thighs  ', 'folder'=>'Back','filename'=>'barbell-good-morning-female_thighs_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Reverse Grip Bent Over Row Female Back ', 'folder'=>'Back','filename'=>'barbell-reverse-grip-bent-over-row-female_back_360.gif','muscle_group_id'=>3,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Reverse Grip Bent Over Row Back Fix 180', 'folder'=>'Back','filename'=>'barbell-reverse-grip-bent-over-row_back-fix_180.gif','muscle_group_id'=>3,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Reverse Grip Incline Bench Row Back ', 'folder'=>'Back','filename'=>'barbell-reverse-grip-incline-bench-row_back_360.gif','muscle_group_id'=>3,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Shrug Back ', 'folder'=>'Back','filename'=>'barbell-shrug_back_360.gif','muscle_group_id'=>3,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Bird Dog Female  ', 'folder'=>'Back','filename'=>'bird-dog-female_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Lateral Pulldown With Rope Attachment Back  ', 'folder'=>'Back','filename'=>'cable-lateral-pulldown-with-rope-attachment_back_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Standing Rear Delt Row With Rope Shoulder  ', 'folder'=>'Back','filename'=>'cable-standing-rear-delt-row-with-rope_shoulder_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Wide Grip Lat Pulldown Female Back 720 410X200', 'folder'=>'Back','filename'=>'cable-wide-grip-lat-pulldown-female_back_720-410x200.gif','muscle_group_id'=>3,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Bent Over Row Back Fix  ', 'folder'=>'Back','filename'=>'dumbbell-bent-over-row_back-fix_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Bent Over Row Back Back ', 'folder'=>'Back','filename'=>'dumbbell-bent-over-row_back_back_360.gif','muscle_group_id'=>3,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Pronated Grip Row  Female Back  ', 'folder'=>'Back','filename'=>'dumbbell-pronated-grip-row-_female_back_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Shrug Back Fix ', 'folder'=>'Back','filename'=>'dumbbell-shrug_back-fix_360.gif','muscle_group_id'=>3,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Hyperextension Hyperextensions Geraet Ohne Gewicht ', 'folder'=>'Back','filename'=>'hyperextension-hyperextensions_geraet_ohne_gewicht-360x200.gif','muscle_group_id'=>3,'equipment_id'=>15,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Back Extension Waist  1', 'folder'=>'Back','filename'=>'lever-back-extension_waist_360-1.gif','muscle_group_id'=>3,'equipment_id'=>2,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Bent Over Row Plate Loaded Female Back  ', 'folder'=>'Back','filename'=>'lever-bent-over-row-plate-loaded-female_back_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Gripless Shrug Version 2 Back  ', 'folder'=>'Back','filename'=>'lever-gripless-shrug-version-2_back_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Smith Bent Knee Good Morning Hips  ', 'folder'=>'Back','filename'=>'smith-bent-knee-good-morning_hips_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>22,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Superman Waist   (1)', 'folder'=>'Back','filename'=>'superman_waist_360-360x200 (1).gif','muscle_group_id'=>3,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Superman Waist  ', 'folder'=>'Back','filename'=>'superman_waist_360-360x200.gif','muscle_group_id'=>3,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Wide Grip Pull Up On Dip Cage Back ', 'folder'=>'Back','filename'=>'wide-grip-pull-up-on-dip-cage_back_720.gif','muscle_group_id'=>3,'equipment_id'=>19,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Assisted Weighted Push Up Chest  ', 'folder'=>'Chest','filename'=>'assisted-weighted-push-up_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>25,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band High Fly Chest  ', 'folder'=>'Chest','filename'=>'band-high-fly_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Decline Bench Press Chest  ', 'folder'=>'Chest','filename'=>'barbell-decline-bench-press_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Guillotine Bench Press Chest  ', 'folder'=>'Chest','filename'=>'barbell-guillotine-bench-press_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Incline Bench Press Chest  ', 'folder'=>'Chest','filename'=>'barbell-incline-bench-press_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Standing Up Straight Crossovers Female Chest  ', 'folder'=>'Chest','filename'=>'cable-standing-up-straight-crossovers-female_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Close Grip Push Up Upper Arms  ', 'folder'=>'Chest','filename'=>'close-grip-push-up_upper-arms_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Decline Push Up On Stability Ball Chest ', 'folder'=>'Chest','filename'=>'decline-push-up-on-stability-ball_chest_360.gif','muscle_group_id'=>4,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Decline Bench Press Chest  ', 'folder'=>'Chest','filename'=>'dumbbell-decline-bench-press_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Fly Chest Fix  ', 'folder'=>'Chest','filename'=>'dumbbell-fly_chest-fix_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Incline Fly Chest Fix  1 ', 'folder'=>'Chest','filename'=>'dumbbell-incline-fly_chest-fix_360-1-360x200.gif','muscle_group_id'=>4,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Reverse Bench Press Chest  ', 'folder'=>'Chest','filename'=>'dumbbell-reverse-bench-press_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Isometric Wipers Chest  ', 'folder'=>'Chest','filename'=>'isometric-wipers_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Seated Fly Female Chest  ', 'folder'=>'Chest','filename'=>'lever-seated-fly-female_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>null,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Push Up Bosu Ball Chest  ', 'folder'=>'Chest','filename'=>'push-up-bosu-ball_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>5,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Push Up M Chest Fix  ', 'folder'=>'Chest','filename'=>'push-up-m_chest-fix_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Push Up On Knees Chest  ', 'folder'=>'Chest','filename'=>'push-up-on-knees_chest_360-360x200.gif','muscle_group_id'=>4,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Push Up On Stability Ball Chest ', 'folder'=>'Chest','filename'=>'push-up-on-stability-ball_chest_360.gif','muscle_group_id'=>4,'equipment_id'=>23,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Raise Single Leg Push Up Chest ', 'folder'=>'Chest','filename'=>'raise-single-leg-push-up_chest_360.gif','muscle_group_id'=>4,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'45 Degree One Leg Hyperextension Arms In Front Of Chest Hips ', 'folder'=>'Core','filename'=>'45-degree-one-leg-hyperextension-arms-in-front-of-chest_hips_360.gif','muscle_group_id'=>1,'equipment_id'=>15,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'45 Degree Twisting Hyperextension Hips  1', 'folder'=>'Core','filename'=>'45-degree-twisting-hyperextension_hips_360-1.gif','muscle_group_id'=>1,'equipment_id'=>15,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Air Bike M Waist Fix  (1)', 'folder'=>'Core','filename'=>'air-bike-m_waist_fix_360 (1).gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Air Bike M Waist Fix ', 'folder'=>'Core','filename'=>'air-bike-m_waist_fix_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Air Twisting Crunch Waist ', 'folder'=>'Core','filename'=>'air-twisting-crunch_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Alternate Lying Floor Leg Raise Waist ', 'folder'=>'Core','filename'=>'alternate-lying-floor-leg-raise_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Twist Down Up Waist ', 'folder'=>'Core','filename'=>'band-twist-down-up_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Twist Up Down Waist  1', 'folder'=>'Core','filename'=>'band-twist-up-down_waist_360-1.gif','muscle_group_id'=>1,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell One Leg Hip Thrust Hips ', 'folder'=>'Core','filename'=>'barbell-one-leg-hip-thrust_hips_360.gif','muscle_group_id'=>1,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Bird Dog Female ', 'folder'=>'Core','filename'=>'bird-dog-female_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Kneeling Crunch Female Waist ', 'folder'=>'Core','filename'=>'cable-kneeling-crunch-female_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Close Grip Push Up Upper Arms ', 'folder'=>'Core','filename'=>'close-grip-push-up_upper-arms_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Floor W Waist ', 'folder'=>'Core','filename'=>'crunch-floor-w_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Hands Overhead Waist ', 'folder'=>'Core','filename'=>'crunch-hands-overhead_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Crunch Straight Leg Up Waist ', 'folder'=>'Core','filename'=>'crunch-straight-leg-up_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Decline Sit Up Arms Straight Waist ', 'folder'=>'Core','filename'=>'decline-sit-up-arms-straight_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Frog Crunch Waist ', 'folder'=>'Core','filename'=>'frog-crunch_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Front Plank With Arm And Leg Lift Push Up Position Female ', 'folder'=>'Core','filename'=>'front-plank-with-arm-and-leg-lift-push-up-position-female_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Hip Crunch Knees Bent Waist  1', 'folder'=>'Core','filename'=>'hip-crunch-knees-bent_waist_360-1.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Isometric Wipers Chest ', 'folder'=>'Core','filename'=>'isometric-wipers_chest_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Jack Knife On Ball Waist ', 'folder'=>'Core','filename'=>'jack-knife-on-ball_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>23,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Jackknife Sit Up Waist ', 'folder'=>'Core','filename'=>'jackknife-sit-up_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Back Extension Waist  1', 'folder'=>'Core','filename'=>'lever-back-extension_waist_360-1.gif','muscle_group_id'=>1,'equipment_id'=>2,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Mountain Climber Lunge Cardio ', 'folder'=>'Core','filename'=>'mountain-climber-lunge_cardio_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Side Lunge Stretch Thighs ', 'folder'=>'Core','filename'=>'side-lunge-stretch_thighs_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Side Plank M Waist ', 'folder'=>'Core','filename'=>'side-plank-m_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Sit Up Ii Waist ', 'folder'=>'Core','filename'=>'sit-up-ii_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Stability Ball Rollout On Knees Female Hips Fix ', 'folder'=>'Core','filename'=>'stability-ball-rollout-on-knees-female_hips-fix_360.gif','muscle_group_id'=>1,'equipment_id'=>23,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Superman Waist ', 'folder'=>'Core','filename'=>'superman_waist_360.gif','muscle_group_id'=>1,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Ankle Dorsal Flexion Calves ', 'folder'=>'Legs_Glutes','filename'=>'ankle-dorsal-flexion_calves_360.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Band Bent Over Hip Extension Hips  ', 'folder'=>'Legs_Glutes','filename'=>'band-bent-over-hip-extension_hips_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>20,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Bench Front Squat Thighs ', 'folder'=>'Legs_Glutes','filename'=>'barbell-bench-front-squat_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Deadlift Female Hips 720 410X200', 'folder'=>'Legs_Glutes','filename'=>'barbell-deadlift-female_hips_720-410x200.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Full Squat Side Pov Thighs ', 'folder'=>'Legs_Glutes','filename'=>'barbell-full-squat-side-pov_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Hip Thrust Female Hips ', 'folder'=>'Legs_Glutes','filename'=>'barbell-hip-thrust-female_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Hip Thrust Hips ', 'folder'=>'Legs_Glutes','filename'=>'barbell-hip-thrust_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Lateral Lunge Hips  1', 'folder'=>'Legs_Glutes','filename'=>'barbell-lateral-lunge_hips_360-1.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Lunge Thighs ', 'folder'=>'Legs_Glutes','filename'=>'barbell-lunge_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell One Leg Hip Thrust Hips ', 'folder'=>'Legs_Glutes','filename'=>'barbell-one-leg-hip-thrust_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Single Leg Split Squat Female Thighs ', 'folder'=>'Legs_Glutes','filename'=>'barbell-single-leg-split-squat-female_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Sumo Squat Thighs  ', 'folder'=>'Legs_Glutes','filename'=>'barbell-sumo-squat_thighs_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Barbell Zercher Squat Hips ', 'folder'=>'Legs_Glutes','filename'=>'barbell-zercher-squat_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Bird Dog Male Back  1', 'folder'=>'Legs_Glutes','filename'=>'bird-dog-male_back_360-1.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Cable Hip Abduction Version 2 Hips ', 'folder'=>'Legs_Glutes','filename'=>'cable-hip-abduction-version-2_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>7,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Bench Squat Female Thighs  ', 'folder'=>'Legs_Glutes','filename'=>'dumbbell-bench-squat-female_thighs_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Bulgarian Split Squat Female Thighs ', 'folder'=>'Legs_Glutes','filename'=>'dumbbell-bulgarian-split-squat-female_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Deadlift Back ', 'folder'=>'Legs_Glutes','filename'=>'dumbbell-deadlift_back_360.gif','muscle_group_id'=>5,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Forward Leaning Lunge Thighs  ', 'folder'=>'Legs_Glutes','filename'=>'dumbbell-forward-leaning-lunge_thighs_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Lunge Female Thighs  ', 'folder'=>'Legs_Glutes','filename'=>'dumbbell-lunge-female_thighs_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Rear Lunge Female Thighs  1 ', 'folder'=>'Legs_Glutes','filename'=>'dumbbell-rear-lunge-female_thighs_360-1-360x200.gif','muscle_group_id'=>5,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Dumbbell Step Up Single Leg Balance With Bicep Curl Upper Arms ', 'folder'=>'Legs_Glutes','filename'=>'dumbbell-step-up-single-leg-balance-with-bicep-curl_upper-arms_360.gif','muscle_group_id'=>5,'equipment_id'=>11,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Exercise Ball Wall Squat Thighs ', 'folder'=>'Legs_Glutes','filename'=>'exercise-ball-wall-squat_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>12,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'High Knee Twist Cardio ', 'folder'=>'Legs_Glutes','filename'=>'high-knee-twist_cardio_360.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Horizontal Leg Press Thighs  ', 'folder'=>'Legs_Glutes','filename'=>'lever-horizontal-leg-press_thighs_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>17,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Seated Calf Raise Plate Loaded Version 2 Calves ', 'folder'=>'Legs_Glutes','filename'=>'lever-seated-calf-raise-plate-loaded-version-2_calves_360.gif','muscle_group_id'=>5,'equipment_id'=>8,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Seated Hip Abduction Hips Fix  1 ', 'folder'=>'Legs_Glutes','filename'=>'lever-seated-hip-abduction_hips-fix_360-1-360x200.gif','muscle_group_id'=>5,'equipment_id'=>14,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Lever Seated Hip Adduction Thighs  ', 'folder'=>'Legs_Glutes','filename'=>'lever-seated-hip-adduction_thighs_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>14,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Pistol Squat To Box Female Thighs  2', 'folder'=>'Legs_Glutes','filename'=>'pistol-squat-to-box-female_thighs_360-2.gif','muscle_group_id'=>5,'equipment_id'=>4,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Side Hip Abduction Hips ', 'folder'=>'Legs_Glutes','filename'=>'side-hip-abduction_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Side Lunge Stretch Thighs  ', 'folder'=>'Legs_Glutes','filename'=>'side-lunge-stretch_thighs_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Side Lying Clam Hips ', 'folder'=>'Legs_Glutes','filename'=>'side-lying-clam_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Single Leg Hip Bridge Straight Leg Hips  ', 'folder'=>'Legs_Glutes','filename'=>'single-leg-hip-bridge-straight-leg_hips_360-360x200.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Sit Squat Thighs ', 'folder'=>'Legs_Glutes','filename'=>'sit-squat_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Split Squats Thighs ', 'folder'=>'Legs_Glutes','filename'=>'split-squats_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Standing Hip Abduction Hips ', 'folder'=>'Legs_Glutes','filename'=>'standing-hip-abduction_hips_360.gif','muscle_group_id'=>5,'equipment_id'=>18,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Strongman Front Chest Squat Weightlifting ', 'folder'=>'Legs_Glutes','filename'=>'strongman-front-chest-squat_weightlifting_360.gif','muscle_group_id'=>5,'equipment_id'=>3,'created_at'=>now(),'updated_at'=>now()],
            ['name'=>'Trap Bar Deadlift Thighs ', 'folder'=>'Legs_Glutes','filename'=>'trap-bar-deadlift_thighs_360.gif','muscle_group_id'=>5,'equipment_id'=>24,'created_at'=>now(),'updated_at'=>now()]


        ]);
    }
}
